import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "GENOME",
  description: "Generated by EY",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen">
        <ToastContainer />
        <div className="flex flex-col h-screen max-w-screen">
          <div className="h-16">
            <Navbar />
          </div>
          <main className="flex-grow">{children}</main>
        </div>
      </body>
    </html>
  );
}
