import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "GENOME",
  description: "Generated by EY",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full overflow-hidden" suppressHydrationWarning>
        <ToastContainer />
        <div className="flex flex-col h-full overflow-hidden">
          <div className="h-16 shrink-0">
            <Navbar />
          </div>
          <main className="flex-1 overflow-hidden">{children}</main>
        </div>
      </body>
    </html>
  );
}
